### ISSUE TITLE
losing focus

### ISSUE THREAD

**Issue by V1ktorino** [ptcong/js-popunder#5]
Hey. my English not so good, but i try to explain my self clear.
Until today the plugin works perfect, open new tab in browser and staying with focus on current page.
Now  it's losing focus from page  and when popunder open, the focus going on him and not on window that open him.

**Comment by ptcong** [comment]
I'm understand that you want to mention losing blur feature.
As i have noted in version 2.2, blur feature now not works on chrome 41+.
Because on chrome, new tab in background (blur) work like you hold on ctrl and click to a link. 
In version 41, chrome have fixed the hack, also popup can’t blur now.
In firefox, blur + pop new window still works.

The problem has occurred a few days ago, but now you see it because your chrome just updated to version 41+ today.

I have try to make some cases to pass this issue, but still failed.

Now 
Firefox + blur + new tab = failed
Firefox + blur + new window = **blur ok**
Chrome + blur + new tab = failed
Chrome + blur + new window = failed

**Comment by gibigate** [comment]
any news?

**Comment by V1ktorino** [comment]
don't think. but i found one more bug  with defining browsers  versions. a bug is with IE 11 and i fixed this, tomorow i put here the fix, that you can see it.

**Comment by ptcong** [comment]
@V1ktorino  you mean IE 11's version become 7 ? 
Because i use simple detection with `trident/7.0`, and in the code we don't use anything about IE11 so just for temporary :D

**Comment by V1ktorino** [comment]
no. the regex in browser object, not good for iE11.
here is my solution.

`msie: (/msie/.test(userAgent) || /rv:11/.test(userAgent)) && !/opera/.test(userAgent),`

`version: (!!userAgent.match(/trident.*rv[ :]*11\./)) ?  userAgent.match(/trident.*rv[ :]*(11)\./)[1] : userAgent.match(/[^\s]+(?:ri|ox|me|ra|ie)\/([\d]+)/i)[1]`

**Comment by ptcong** [comment]
Ok, i just release new version for this patch, check it.

**Comment by ptcong** [comment]
Google Chrome killed the feature, can't bypass.

**Comment by ptcong** [comment]
I have released a new version that bring back the feature, works on firefox, chrome.

**Comment by V1ktorino** [comment]
nice!
